//
// Created by Edouard LAFARGE on 20/03/2025.
//

#ifndef PAULGIRAULT_EDOUARDLAFARGE_PROJETC_BMP8_COULEUR_H
#define PAULGIRAULT_EDOUARDLAFARGE_PROJETC_BMP8_COULEUR_H

#endif //PAULGIRAULT_EDOUARDLAFARGE_PROJETC_BMP8_COULEUR_H
