//
// Created by Edouard LAFARGE on 20/03/2025.
//

#ifndef PAULGIRAULT_EDOUARDLAFARGE_PROJETC_MENU_H
#define PAULGIRAULT_EDOUARDLAFARGE_PROJETC_MENU_H

#endif //PAULGIRAULT_EDOUARDLAFARGE_PROJETC_MENU_H
