#ifndef PAULGIRAULT_EDOUARDLAFARGE_PROJETC_MENU_H
#define PAULGIRAULT_EDOUARDLAFARGE_PROJETC_MENU_H

int Menu();
int menu_filtres();
int menu_filtres_couleur();

#endif //PAULGIRAULT_EDOUARDLAFARGE_PROJETC_MENU_H
